### ISSUE TITLE
Use tar_read_raw()

### ISSUE THREAD

**Issue by wlandau** [databio/unitar#2]
`unitar_load()` calls `readRDS()` to load data:

https://github.com/databio/unitar/blob/237058256f6ac36b5d063458917f8505d4db8581/R/unitar.R#L71

Maybe use `tar_read_raw()` instead? That way, if a target has a local storage format other than `"rds"`, `unitar_load()` will still be able to read it.

**Comment by nsheff** [comment]
excellent, I will update that.
