### ISSUE TITLE
Target factory to take output from one pipeline as input into another

### ISSUE THREAD

**Issue by wlandau** [databio/unitar#3]
As I propose in https://github.com/ropensci/targets/discussions/297#discussioncomment-476243, it may be possible to take output from one pipeline (A) as input into another pipeline (B). For local files, this would rely on file tracking. ("url" and "aws_*" storage formats would need different workarounds.) Sketch of the tar_target() calls:

```r
# _targets.R
# ...
list(
  tar_target(file_a, unitar_path(...), format = "file").
  tar_target(data_a, unitar_read_from_path(file_a))
)
```

unitar_read_from_path() would need to be defined separately. Given a path like `.../project_a/_targets/objects/target_a`, it could call `withr::with_dir("../project_a", tar_read_raw("target_a"))` or something like that.

It should be possible to simplify the above two target calls down to a single [target factory](https://wlandau.github.io/targetopia/contributing.html#target-factories):

```r
# _targets.R
# ...
list(
  tar_unitar_read(new_name, "other_pipeline_dir", "target_name_in_other_pipeline")
)
```

**Comment by nsheff** [comment]
Ok, I think I follow most of this and it's great. I have a question to make sure I'm thinking about it correctly --  why can't you just use the existing `unitar_read` to just do this right away, and bypass the multi-step approach above that requires a target factory?

```r
# _targets.R
# ...
list(
  unitar_read(new_name, "other_pipeline_dir", "target_name_in_other_pipeline")
)
```

This is in fact how `unitar_read` already works. Do you have to do the above 2-step approach, with a target factory, to enable the file tracking correctly so that if the cache changes in the "other_pipeline" it will automatically trigger downstream changes in the current one? Am I thinking about this correctly?

**Comment by wlandau** [comment]
Hi @nsheff,

Yes, the `format = "file"` target tracks the original file from `project_a` for changes. If you just use `unitar_read()`, then updates in `project_a` would fail to invalidate the downstream targets in `project_b`.

By the way, I realize https://github.com/ropensci/targets/discussions/297 was the original inspiration for `unitar`, especially while I was resisting support for storage paths other than `_targets`. I hope https://github.com/ropensci/targets/pull/407 did not invalidate your hard work.

**Comment by nsheff** [comment]
Got it. I almost have this implemented.

The way I understand it, https://github.com/ropensci/targets/pull/407 is allowing you to store target caches in locations other than the canonical `_targets/objects` folder. That's a start, but you still can only specify a single location for a project right?

What I wanted to do was to easily load targets across projects. That means one project could load targets from another one. So, the rationale for unitar still stands. 

My implementation is quite simple, and it should work nicely even with the updates you're making with the _targets config. In fact, there might be room for even more synergy, as I could read a list of folder paths from _targets.

Anyway, the way I see it, these are complementary advances.

**Comment by wlandau** [comment]
> The way I understand it, ropensci/targets#407 is allowing you to store target caches in locations other than the canonical _targets/objects folder. That's a start, but you still can only specify a single location for a project right?

Right, it's still one data store per project, unless you plan on switching around frequently using `tar_config_set(store = ...)`.

> What I wanted to do was to easily load targets across projects. That means one project could load targets from another one. So, the rationale for unitar still stands.
>
> My implementation is quite simple, and it should work nicely even with the updates you're making with the _targets config. In fact, there might be room for even more synergy, as I could read a list of folder paths from _targets.
>
> Anyway, the way I see it, these are complementary advances.

Glad to hear it!

**Comment by nsheff** [comment]
Ok I've implemented this, and also I added some instructions in the vignette. I included a demo that uses this factory, and I've realized with this there are 3 ways to use unitar:

1. Just load data computed in other projects. Don't track it at all in the current project, just re-use it, and let all tracking happen in the external project. This is the basic case I had already implemented.
2. Load external targets and also track them here. Duplicate those caches into local caches. If the external data changes, it will update the local caches, and all local files for the current project. This is the mode that is enabled with the target factory in this issue.
3. Load external targets and track the original files here, but don't duplicate them into here. This can you do by just adding a "file" target with the external target file, and then writing functions that use this to produce whatever derived targets you need. This way, your targets will update if the external target changes, but you don't have to pay the cost of storing the cache twice. 

I showed how to do all these things in the demo. The one that is most useful to me is case 3. What do you think?

**Comment by wlandau** [comment]
Nice work, @nsheff! Those options and the vignette explaining them look thoughtful and thorough to me. I fully agree with the choices and tradeoffs you identify. (2) and (3) both watch the file in the upstream project, and it is just a matter of choosing between convenience at the interface level and storage efficiency. I think it might be difficult to make a sufficiently flexible target factory for (3).

**Comment by nsheff** [comment]
Alright this looks great. I revamped the vignette now to make these 3 modes of operation more clear and I think this is really useful. Thanks for your input.
